<?php

/**
 * @file
 * Contains fourspots.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fourspots_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fourspots module.
    case 'help.page.fourspots':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('this is a test module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fourspots_theme() {
  return [
    'fourspots' => [
      'render element' => 'children',
    ],
  ];
}
