<?php

/**
 * @file
 * Contains webform_handler_user_creation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_handler_user_creation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_handler_user_creation module.
    case 'help.page.webform_handler_user_creation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will add user creation handle to the webform') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webform_handler_user_creation_theme() {
  return [
    'webform_handler_user_creation' => [
      'render element' => 'children',
    ],
  ];
}
